name: Full CI Workflow
on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      - name: Run Black (check only)
        run: black --check .

      - name: Run Ruff
        run: ruff check .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run Pytest with coverage
        run: pytest --cov=codingbat --cov=leetcode --cov-report=xml:coverage.xml

      - name: Upload coverage XML for next step
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  coverage-upload:
    name: Upload Coverage to Codecov
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download coverage XML artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-xml
          path: .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
